#!/usr/bin/env bash
#
# Stitch the Dragonfly Internals chapters into a single combined Markdown file
# for one-shot distribution (printing, sharing, or feeding to an LLM).
#
# The chapter *order* is read from README.md's table of contents, so this
# script never needs editing when chapters are added, removed, or reordered:
# just keep README.md's TOC correct.
#
# Usage:
#   ./build.sh                       # writes dragonfly-internals-full.md
#   ./build.sh path/to/output.md     # writes to a custom path
#
set -euo pipefail

cd "$(dirname "$0")"

OUT="${1:-dragonfly-internals-full.md}"

# Extract, in order of first appearance in README.md, every local link that
# points at a chapter or the glossary (./NN-*.md or ./glossary.md). The
# ../implementation-notes.md appendix and README itself are intentionally
# excluded. Dedupe while preserving order. (Portable to bash 3.2 — no mapfile.)
# Only scan the "Table of contents" section so ordering follows the curated
# Part sequence (chapters first, glossary last) and ignores stray links in the
# prose above it.
FILES=()
while IFS= read -r f; do
  FILES+=("$f")
done < <(
  awk '/^## Table of contents/{t=1; next} t' README.md \
    | grep -oE '\(\./([0-9]+-[a-z0-9-]+|glossary)\.md\)' \
    | sed -E 's/^\(\.\///; s/\)$//' \
    | awk '!seen[$0]++'
)

if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "error: no chapter links found in README.md" >&2
  exit 1
fi

{
  echo "# Dragonfly Internals"
  echo
  echo "*How a modern, multi-threaded, Redis- and Memcached-compatible data store works on the inside.*"
  echo
  echo "> Single-file build generated by \`build.sh\` on $(date -u +%Y-%m-%d). The chapter"
  echo "> sources under \`dragonfly-internals/\` remain the source of truth; edit those, not this file."
  echo

  for f in "${FILES[@]}"; do
    if [[ ! -f "$f" ]]; then
      echo "error: README references missing file: $f" >&2
      exit 1
    fi
    echo
    echo "---"
    echo
    cat "$f"
    echo
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines) from ${#FILES[@]} files:"
printf '  %s\n' "${FILES[@]}"
